[package]
name = "_21_web_scrapper"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.23", features = ["blocking", "rustls-tls"] }
scraper = "0.24.0"
thiserror = "2.0.16"
